### PR TITLE
Fixes cos url

### PR DESCRIPTION
**Pull request by plcstpierre**

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Could you tell me more about this change? Is there documentation on the Google Cloud site with a list of these? Sorry, it's been a while since I made this, and I'm pretty sure I was just referencing an upstream list.

**Comment by plcstpierre** [comment]
Current images: https://cloud.google.com/compute/docs/images
Rename announce: https://groups.google.com/forum/#!topic/gce-announce/v9JSnre92I8
Release history: https://cloud.google.com/container-optimized-os/docs/release-notes (you can see the rename gci to cos)

**Comment by plcstpierre** [comment]
You can also try running your test :) they will fail ;)

**Comment by plcstpierre** [comment]
@stephenplusplus poke :)

**Comment by stephenplusplus** [comment]
Sorry! Thank you! Merged!

**Comment by stephenplusplus** [comment]
Published under 0.3.4.

**Pull request merged**
